project_id = "mkhqhlrxkabqqmzgzhwx"

[auth]
hook_send_email_enabled = false

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email-token]
verify_jwt = false

[functions.resend-verification]
verify_jwt = false