project_id = "mkhqhlrxkabqqmzgzhwx"

[auth]
hook_send_email_enabled = true
hook_send_email_uri = "https://mkhqhlrxkabqqmzgzhwx.supabase.co/functions/v1/send-auth-email"

[functions.send-auth-email]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.handle-razorpay-webhook]
verify_jwt = false
