// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mkhqhlrxkabqqmzgzhwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1raHFobHJ4a2FicXFtemd6aHd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4OTYzMDEsImV4cCI6MjA2OTQ3MjMwMX0.aQ4rrc9tyQ05b2BEV1EnntQouVdYQE297Sgb3kkOAOw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});